language: php
php:
  - "7.2"
sudo: false
script:
  - composer require nunomaduro/phpinsights --dev &&
    ./vendor/bin/phpinsights --no-interaction --min-quality=80 --min-complexity=80 --min-architecture=80 --min-style=60;